from config.connection import Connection
from bson.objectid import ObjectId
from time import sleep
from prettytable import PrettyTable
from models.alumnos import Alumno
from models.profesor import Profesor
from models.cursos import Cursos
from models.grado import Grado
from models.nivel import Nivel
from models.periodo import Periodo
from models.salon import Salon
from models.seccion import Seccion
from models.cursos_docente import CursosDocente